### ISSUE TITLE
Wrong unit

### ISSUE THREAD

**Issue by stefanhintermayr** [Vip0r/vartastorage#21]
![image](https://github.com/user-attachments/assets/8499e563-ca2f-4546-94e0-6ba5ad9e8fe8)

The unit of “Varta Total Power charged” is wrong, it is kWh. But it is Wh.

**Comment by Vip0r** [comment]
Are you sure? The values are from the Modbus register 1069/1070. According to the documentaiton available to me this register is in WH (see attached)

![Image](https://github.com/user-attachments/assets/49399bba-2664-4c6a-98bf-87dd34105b97)

**Comment by stefanhintermayr** [comment]
I understand what you mean, but look for yourself, that is the value from the Varta portal. The storage unit was put into operation in August 2013, any other values ​​would make no sense.

![image](https://github.com/user-attachments/assets/bd35e05c-bad0-456e-be17-9584fc3a7f9e)

![image](https://github.com/user-attachments/assets/ada1cfdc-a77b-4c2f-b956-ccac611f45d9)

**Comment by stefanhintermayr** [comment]
Well, it could be Wh, but then the separators are wrong. Then the last "," would also have to be a dot as a thousands separator.

**Comment by Vip0r** [comment]
Hmm... i understand. I have adjusted the unit of measurement from WATT_HOUR to KILO_WATT_HOUR. Please update the integration and try it again.

(could be the case that you need to delete the entity and let them be re-created by the integration)

**Comment by stefanhintermayr** [comment]
Hmmm... always Wh, but with right values.

![Image](https://github.com/user-attachments/assets/80f8d494-209b-40dc-8606-0ef7f2b4feb9)

**Comment by Vip0r** [comment]
Yeah, seems like HA did not change the unit of measure once an entity was created. In the code i have adjusted it meanwhile.

Please try the following:

Browse to Settings > Entities > Entities > Search for the Entity > Click on the gear in the upper right corner > Change the unit there to kWh

**Comment by stefanhintermayr** [comment]
I found it, thank for your help. :-)

**Comment by Vip0r** [comment]
> I would like to add this error.
> 
> * Power From Grid is shown as W, but it is Wh
> * Power To Grid is shown as W, but it is Wh
> * Total Power Charged are Wh, but is now correctly converted to kWh
> * Total Power Charged is displayed as kWh, but it is Wh
> 
> The following values ​​are read twice. Once in W and once in kWh...
> 
> * Power From Grid is displayed as kWh, but it is Wh
> * Total Power To Grid is shown as kWh, but it is Wh
> 
> It would be great if all values ​​were displayed uniformly in kWh. Is generally more common than Wh.
> 
> Charging Cycle Counter, could the brackets [ ] be removed here?

Thanks. please find below my feedback and some questions for clarification:

* Power From Grid is shown as W, but it is Wh
* Power To Grid is shown as W, but it is Wh

* Total Power Charged are Wh, but is now correctly converted to kWh
* Total Power Charged is displayed as kWh, but it is Wh
> * Power From Grid is displayed as kWh, but it is Wh
> * Total Power To Grid is shown as kWh, but it is Wh

=> I have now changed for all total values the native unit of measurement to KILO_WATT_HOUR. Could you please test?
=> Please note, an update of the integration does not adjust the unit of measurements as i found. So you either need to delete the integration and entities or you manually can adjust the measurements in the properties of the entity
=> Removed also the two duplicates

Charging Cycle Counter, could the brackets [ ] be removed here?
=> fixed

**Comment by Vip0r** [comment]
Okay.. i am still confused. Could it be that there are in fact some values need to be displayed as wH while some others are kWh? (see my screenshot)

![Image](https://github.com/user-attachments/assets/f825b428-cc76-417f-bd27-6843b3348215)

**Comment by zoomy01** [comment]
I deleted the integration and re-added it.

The duplicates and the brackets are gone.

However, the values ​​are still not correct. In the web interface the values ​​are all displayed in Wh. If you also format the entities in Wh, then it would be identical to the original data. Personally, I would find kWh more plausible.

One decimal place would be sufficient as default.

Total Power Charged is now correctly formatted and converted to kWh.

Total Power From Grid and Total Power To Grid would have to be divided by 1000, then it would fit into kWh.

![Image](https://github.com/user-attachments/assets/83e1baeb-8eb8-41a1-aaec-d55b8fd7ea27)

![Image](https://github.com/user-attachments/assets/83f03182-80ce-46dd-bd87-1bfaaa61f1b8)

**Comment by Vip0r** [comment]
got it. Will for the moment now switch to WATT_HOUR as this are the format the numbers are provided. In a next step i see if i can convert in the integration itself

**Comment by zoomy01** [comment]
Wh is of course also fine.

However, VARTA Total Power Charged is still issued in kWh. It would be nice if all values ​​were uniformly formatted in Wh.

![Image](https://github.com/user-attachments/assets/ba4c1bb7-ad9d-44e6-85e4-8a0510518345)

I also noticed that VARTA Apparent Power does not correspond to Watt but to VA. Here the unity is wrong.

![Image](https://github.com/user-attachments/assets/1d215987-d31a-4cf8-a657-aa6aa8358cca)

**Comment by Vip0r** [comment]
Regarding Totals:

Yep - it's true that Total Power Charged is kWw. But according to the decimal seperators this should be right. Isn't it ? I would also prefer to have this in the same unit. But at the moment the device provides the Total Power Charged in kWh and the other in wH. Without manually converting the date (which i consider to do in the future) this should now be the correct visualization of the data provided "as is". Correct?

Regarding Apparent Power:

Good point. Have modified the unit - with the next update it should appear as VA. Thx!

**Comment by zoomy01** [comment]
Total Power Charged is also Wh. But in the code it is divided by 1000.

`res = ((res_high << 16) | (res_low & 0xFFFF)) / 1000`

Can you change it to Wh then it would be uniform?

By the way...

VARTA Installed Capacity is also Wh. Unfortunately I just noticed it.

**Comment by Vip0r** [comment]
> Total Power Charged is also Wh. But in the code it is divided by 1000.
> 
> `res = ((res_high << 16) | (res_low & 0xFFFF)) / 1000`
> 
> Can you change it to Wh then it would be uniform?
> 
> By the way...
> 
> VARTA Installed Capacity is also Wh. Unfortunately I just noticed it.

Yep - you are absolutely right. As this is also manually converted into kWh i will try to do the same for the other values. I think as we aligned it would be the best case to have everything in kWh. Will take a look into it in the next days

**Comment by Vip0r** [comment]
in the latest release i now have converted all totals to kWh. Thanks for your feedback!
